# Generated by Django 2.2 on 2019-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(help_text='Add image related to your blog', upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.CharField(help_text='Add something about author', max_length=1000),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Add picture of author', null=True, upload_to=''),
        ),
    ]
