# Generated by Django 2.2 on 2019-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0007_auto_20191110_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['author_name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='True', max_length=250),
            preserve_default=False,
        ),
    ]
