# Generated by Django 2.2 on 2019-11-11 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Organizer Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Organizer Email')),
                ('webiste', models.URLField(blank=True, null=True, verbose_name='Web Address')),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip/Post Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default=True, max_length=250, verbose_name='Category of Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0, help_text='Add cost of event in case of free, write 0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=True, verbose_name='Event Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Event Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(choices=[('o', 'On Time'), ('d', 'Delayed'), ('c', 'Completed')], default='o', help_text='Choose Event Status from here', max_length=1),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=True, max_length=120, verbose_name='Event Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default=True, help_text='Add picture related to event', upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='Events.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Venue'),
            preserve_default=False,
        ),
    ]
