# Generated by Django 2.2 on 2019-11-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20191111_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
