# Generated by Django 2.2 on 2019-11-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=True, max_length=120, verbose_name='Event Name'),
            preserve_default=False,
        ),
    ]
