# Generated by Django 2.2 on 2019-11-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default=True, help_text='Add picture related to event', upload_to=''),
            preserve_default=False,
        ),
    ]
