# Generated by Django 2.2 on 2019-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0012_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=0, help_text='Add cost of event in case of free, write 0'),
            preserve_default=False,
        ),
    ]
