# Generated by Django 2.2 on 2019-11-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(to='Events.RegisteredUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_manager',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Events.Organizer'),
            preserve_default=False,
        ),
    ]
