# Generated by Django 2.2 on 2019-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0015_auto_20191111_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='label',
            field=models.CharField(default=True, max_length=12),
            preserve_default=False,
        ),
    ]
