# Generated by Django 2.2 on 2019-11-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0016_event_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='label',
            field=models.CharField(choices=[('o', 'On Time'), ('d', 'Delayed'), ('c', 'Completed')], default='o', help_text='Choose Event Status from here', max_length=1),
        ),
    ]
