# Generated by Django 2.2 on 2019-11-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0017_auto_20191111_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
    ]
