# Generated by Django 2.2 on 2019-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0020_auto_20191111_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='Events.RegisteredUser'),
        ),
    ]
